### PR TITLE
Update view schemas

### PR DESCRIPTION
**Pull request by cristinaleonr**
This PR adds a new BigQuery client for the views project to update the view schema whenever a table schema is changed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/autoloader/18)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autoloader/18)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`bq/client.go` line 100 at r3](https://reviewable.io/reviews/m-lab/autoloader/18#-NU8hYEG8v9ELFxgbBQh:-NU8hYEG8v9ELFxgbBQi:b-jcdshb) ([raw file](https://github.com/m-lab/autoloader/blob/9fb69433fe5730891a9719c746b62d6c3b32fd2d/bq/client.go#L100)):*
> ```Go
> 	_, err := ds.Metadata(ctx)
> 	if err != nil {
> 		// Dataset doesn't exist. Nothing to update.
> ```

nit: this error could represent other conditions, such as permissions across projects.

it could be hard to diagnose without the err information. doesn't have to be blocking.
___
*[`cmd/autoloader/main.go` line 54 at r3](https://reviewable.io/reviews/m-lab/autoloader/18#-NU8i85w5xtR_LriMVVO:-NU8i85w5xtR_LriMVVP:b-yb8177) ([raw file](https://github.com/m-lab/autoloader/blob/9fb69433fe5730891a9719c746b62d6c3b32fd2d/cmd/autoloader/main.go#L54)):*
> ```Go
> 	bqView := bqMain
> 	if project != viewProject {
> 		bqView, err := bigquery.NewClient(mainCtx, viewProject)
> ```

Does this assignment (using `:=`) WAI outside the block?

https://go.dev/play/p/Pgh266sk3ki

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autoloader/18)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`bq/client_test.go` line 349 at r3](https://reviewable.io/reviews/m-lab/autoloader/18#-NU8ioGRBeuyn720F8LZ:-NU8ioGRBeuyn720F8L_:b-b7ly2j) ([raw file](https://github.com/m-lab/autoloader/blob/9fb69433fe5730891a9719c746b62d6c3b32fd2d/bq/client_test.go#L349)):*
> ```Go
> 			c := &Client{Client: bq, ViewClient: bq}
> 
> 			err = c.UpdateSchema(context.Background(), ds, tt.dt)
> ```

Out of scope for the PR, but I noticed the mixture of `context.Background()` and `context.TODO()` -- I've previously provided feedback about one or the other. I must have missed this mixture. I recommend updating with a future PR with any other fixes / tune ups.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autoloader/18)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`bq/client.go` line 100 at r3](https://reviewable.io/reviews/m-lab/autoloader/18#-NU8hYEG8v9ELFxgbBQh:-NUMxePT2M8RpLgyrwRZ:b9rh72v) ([raw file](https://github.com/m-lab/autoloader/blob/9fb69433fe5730891a9719c746b62d6c3b32fd2d/bq/client.go#L100)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: this error could represent other conditions, such as permissions across projects.

it could be hard to diagnose without the err information. doesn't have to be blocking.
</blockquote></details>

Good point. I added a comment and some logging.
___
*[`bq/client_test.go` line 349 at r3](https://reviewable.io/reviews/m-lab/autoloader/18#-NU8ioGRBeuyn720F8LZ:-NUMvnlJ1ZiPCupi6JcJ:b-kv76e1) ([raw file](https://github.com/m-lab/autoloader/blob/9fb69433fe5730891a9719c746b62d6c3b32fd2d/bq/client_test.go#L349)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Out of scope for the PR, but I noticed the mixture of `context.Background()` and `context.TODO()` -- I've previously provided feedback about one or the other. I must have missed this mixture. I recommend updating with a future PR with any other fixes / tune ups.
</blockquote></details>

They're all `context.Background()` now!
___
*[`cmd/autoloader/main.go` line 54 at r3](https://reviewable.io/reviews/m-lab/autoloader/18#-NU8i85w5xtR_LriMVVO:-NUMxZvb3n6g0Pj5W8vc:b832g0m) ([raw file](https://github.com/m-lab/autoloader/blob/9fb69433fe5730891a9719c746b62d6c3b32fd2d/cmd/autoloader/main.go#L54)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does this assignment (using `:=`) WAI outside the block?

https://go.dev/play/p/Pgh266sk3ki
</blockquote></details>

Good catch!!! Fixed.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/m-lab/autoloader/18#-:-NUN6PHp5lznhRIDpEaj:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
