### PR TITLE
Append the raw_ prefix to experiments from m-lab buckets

### PR DESCRIPTION
**Pull request by cristinaleonr**
This PR appends the "raw_" prefix to experiments under m-lab buckets, so the tables for such datatypes are created under the `raw_experiment` dataset.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/autoloader/12)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autoloader/12)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`gcs/gcs.go` line 81 at r1](https://reviewable.io/reviews/m-lab/autoloader/12#-NSCuDgp6jGAeWNeCGdE:-NSCuDgp6jGAeWNeCGdF:b-jvldez) ([raw file](https://github.com/m-lab/autoloader/blob/71252e5eb69931ba5749551045faa7d86581d268/gcs/gcs.go#L81)):*
> ```Go
> 			exp := path.Base(dir)
> 			if slices.Contains(mlabBuckets, attrs.Name) {
> 				exp = "raw_" + exp
> ```

Is this something jostler should do? That is upload data to a directory name meant to match the ultimate dataset name?

I know we've talked about the autoloader supporting this change, but at this moment, I'm wondering if it would be preferable / simpler overall for the prefix to be added here: https://github.com/m-lab/k8s-support/blob/main/k8s/daemonsets/templates.jsonnet#L345

Then the autoloader can "do one thing well". Would this work?

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autoloader/12)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`gcs/gcs.go` line 81 at r1](https://reviewable.io/reviews/m-lab/autoloader/12#-NSCuDgp6jGAeWNeCGdE:-NSGpREh8mpqZ2KkqBHm:b-dvzfb1) ([raw file](https://github.com/m-lab/autoloader/blob/71252e5eb69931ba5749551045faa7d86581d268/gcs/gcs.go#L81)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this something jostler should do? That is upload data to a directory name meant to match the ultimate dataset name?

I know we've talked about the autoloader supporting this change, but at this moment, I'm wondering if it would be preferable / simpler overall for the prefix to be added here: https://github.com/m-lab/k8s-support/blob/main/k8s/daemonsets/templates.jsonnet#L345

Then the autoloader can "do one thing well". Would this work?
</blockquote></details>

This is something the jostler *could* do. 

That said, I do not think that pipeline abstractions (e.g., `raw_` experiment prefixes) should be reflected in the GCS archives. Since the autoloader is part of the pipeline, I believe it makes more sense for it to be the one to handle such abstractions.

**Review by stephen-soltesz — COMMENTED** [review]
I accept the rationale for "raw_" prefixes managed by the autoloader.

I strongly discourage hard coding project names or buckets into the gcs package. Two suggestions for how to avoid that.

> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/m-lab/autoloader/12#-:-NSIIaBh69yXqTyoYldy:b-ahywp1)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`gcs/gcs.go` line 81 at r1](https://reviewable.io/reviews/m-lab/autoloader/12#-NSCuDgp6jGAeWNeCGdE:-NSIHo5G9cQWBJfgdZM-:b4sw7us) ([raw file](https://github.com/m-lab/autoloader/blob/71252e5eb69931ba5749551045faa7d86581d268/gcs/gcs.go#L81)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

This is something the jostler *could* do. 

That said, I do not think that pipeline abstractions (e.g., `raw_` experiment prefixes) should be reflected in the GCS archives. Since the autoloader is part of the pipeline, I believe it makes more sense for it to be the one to handle such abstractions.


</blockquote></details>

The "raw_" prefixes are an abstraction by/for the pipeline. I like that. sgtm.
___
*[`gcs/gcs.go` line 23 at r4](https://reviewable.io/reviews/m-lab/autoloader/12#-NSII1kYASd0JKyNJwaW:-NSII1kYASd0JKyNJwaX:b-5uhfyn) ([raw file](https://github.com/m-lab/autoloader/blob/a0003c248ba5e1e21ab4f231e0409fd7cb3b29e9/gcs/gcs.go#L23)):*
> ```Go
> var (
> 	suffix      = regexp.MustCompile(`(\d{4}/[01]\d/[0123]\d)/$`)
> 	mlabBuckets = []string{"archive-mlab-sandbox", "archive-mlab-staging", "archive-mlab-oti"}
> ```

Please make this a flag or parameter to the `Client` type. Presumably there will be one instance of the autoloader per project which could easily pass in the project archive as a parameter to treat differently. Also for production, I expect we'll end up using `archive-measurement-lab` not `archive-mlab-oti`.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autoloader/12)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`gcs/gcs.go` line 23 at r4](https://reviewable.io/reviews/m-lab/autoloader/12#-NSII1kYASd0JKyNJwaW:-NSMEmJq3o2SqVkQxqEy:bc58gf7) ([raw file](https://github.com/m-lab/autoloader/blob/a0003c248ba5e1e21ab4f231e0409fd7cb3b29e9/gcs/gcs.go#L23)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please make this a flag or parameter to the `Client` type. Presumably there will be one instance of the autoloader per project which could easily pass in the project archive as a parameter to treat differently. Also for production, I expect we'll end up using `archive-measurement-lab` not `archive-mlab-oti`.
</blockquote></details>

Makes sense. I changed it to a flag!

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/autoloader/12#-:-NSMHuKDBXbq4FFW5ANV:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
