### PR TITLE
Add Load to bq package

### PR DESCRIPTION
**Pull request by cristinaleonr**
This PR adds a new `Client.Load()` method to the `bq` package to load a GCS uri to a BigQuery table.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/autoloader/6)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autoloader/6)* status: 0 of 1 approvals obtained

___
*[`go.mod` line 8 at r1](https://reviewable.io/reviews/m-lab/autoloader/6#-NRdMBmCBOEbiYqjp9xa:-NRdMBmCBOEbiYqjp9xb:b-qrr8ga) ([raw file](https://github.com/m-lab/autoloader/blob/2a57974815f05e1b45ceea30a91ee0b0202b94c4/go.mod#L8)):*
> ```XML
> 	cloud.google.com/go/bigquery v1.49.0
> 	cloud.google.com/go/storage v1.30.0
> 	github.com/m-lab/go v0.1.63-0.20230328171438-e81762c3043e
> ```

Before merge, update this version to the latest `m-lab/go` release including https://github.com/m-lab/go/pull/166.

**Review by stephen-soltesz — APPROVED** [review]
Some style questions.

Mostly :lgtm:

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/autoloader/6#-:-NRdPlj8-uTlFNVt1tBh:b-e5gzx7)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`bq/client_test.go` line 253 at r1](https://reviewable.io/reviews/m-lab/autoloader/6#-NRdNwmREBP60tzEHSHf:-NRdNwmREBP60tzEHSHg:bcp1wla) ([raw file](https://github.com/m-lab/autoloader/blob/2a57974815f05e1b45ceea30a91ee0b0202b94c4/bq/client_test.go#L253)):*
> ```Go
> 		{
> 			name:    "success",
> 			loader:  bqfake.NewLoader(*bqfake.NewJob(&bigquery.JobStatus{}, nil), nil),
> ```

Should `NewLoader` accept a pointer instead of dereferencing the return value of `NewJob`?
___
*[`bq/client_test.go` line 284 at r1](https://reviewable.io/reviews/m-lab/autoloader/6#-NRdOAnw-yRUCUhdMIt1:-NRdOAnw-yRUCUhdMIt2:b64x2kx) ([raw file](https://github.com/m-lab/autoloader/blob/2a57974815f05e1b45ceea30a91ee0b0202b94c4/bq/client_test.go#L284)):*
> ```Go
> 			c := &Client{bq}
> 
> 			err = c.Load(context.Background(), ds, tableID, "gs://fake-bucket/autoload/v1/experiment/datatype/YYYY/MM/DD/*")
> ```

Please use `context.TODO` or `context.Background` consistently. I think either is okay but not both.
___
*[`bq/client_test.go` line 284 at r1](https://reviewable.io/reviews/m-lab/autoloader/6#-NRdPaZA4huA-bQYhfpA:-NRdPaZA4huA-bQYhfpB:b-apgw7e) ([raw file](https://github.com/m-lab/autoloader/blob/2a57974815f05e1b45ceea30a91ee0b0202b94c4/bq/client_test.go#L284)):*
> ```Go
> 			c := &Client{bq}
> 
> 			err = c.Load(context.Background(), ds, tableID, "gs://fake-bucket/autoload/v1/experiment/datatype/YYYY/MM/DD/*")
> ```

Are multiple uri parameters at once worth testing?

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autoloader/6)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`go.mod` line 8 at r1](https://reviewable.io/reviews/m-lab/autoloader/6#-NRdMBmCBOEbiYqjp9xa:-NRdXyBn-mr6l4CvJ_Cb:bb6un1j) ([raw file](https://github.com/m-lab/autoloader/blob/2a57974815f05e1b45ceea30a91ee0b0202b94c4/go.mod#L8)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Before merge, update this version to the latest `m-lab/go` release including https://github.com/m-lab/go/pull/166.
</blockquote></details>

Done
___
*[`bq/client_test.go` line 253 at r1](https://reviewable.io/reviews/m-lab/autoloader/6#-NRdNwmREBP60tzEHSHf:-NRdY1WbCWYx1jUiaN5D:b-896fix) ([raw file](https://github.com/m-lab/autoloader/blob/2a57974815f05e1b45ceea30a91ee0b0202b94c4/bq/client_test.go#L253)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Should `NewLoader` accept a pointer instead of dereferencing the return value of `NewJob`?
</blockquote></details>

Done.
___
*[`bq/client_test.go` line 284 at r1](https://reviewable.io/reviews/m-lab/autoloader/6#-NRdOAnw-yRUCUhdMIt1:-NRdY3HT4uFw7yiUTb8u:bweckn2) ([raw file](https://github.com/m-lab/autoloader/blob/2a57974815f05e1b45ceea30a91ee0b0202b94c4/bq/client_test.go#L284)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please use `context.TODO` or `context.Background` consistently. I think either is okay but not both.
</blockquote></details>

Agreed! Changed to `context.Background`.
___
*[`bq/client_test.go` line 284 at r1](https://reviewable.io/reviews/m-lab/autoloader/6#-NRdPaZA4huA-bQYhfpA:-NRdY7TiEJ1f4M8Oie1U:b-ml5dbb) ([raw file](https://github.com/m-lab/autoloader/blob/2a57974815f05e1b45ceea30a91ee0b0202b94c4/bq/client_test.go#L284)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Are multiple uri parameters at once worth testing?
</blockquote></details>

I added one test case with multiple uris.

**Review by stephen-soltesz — APPROVED** [review]
Thank you! looks good.

> *[Reviewable](https://reviewable.io/reviews/m-lab/autoloader/6#-:-NRdZKq-4RGIGdWejGNe:b809ohu)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
