### PR TITLE
Add travis CI

### PR DESCRIPTION
**Pull request by cristinaleonr**
This PR enables Travis CI on this project. 

It also changes tests in the `bq` package to use fakes from [`bqfake`](https://github.com/m-lab/go/tree/main/cloudtest/bqfake).

I see some [old coverage](https://coveralls.io/github/m-lab/autoloader) being picked up by coveralls. I'm not sure how to refresh it/automatically enable the PR coveralls coverage comment.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/autoloader/5)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
I updated the coveralls settings to enable PR reports. So, if you push another change, it should show up as you expect. This is necessary for all new repos. (Also it looks like the warning at the top of the page means we'll eventually need to update how we configure coveralls for most of our repos, but that's another matter).



One suggestion: :lgtm:

> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/autoloader/5#-:-NRFcV5t9xX5KJV3IqVV:b-yddez2)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`bq/client_test.go` line 182 at r1](https://reviewable.io/reviews/m-lab/autoloader/5#-NRFc9yU6IxQ8BpXic2V:-NRFc9yU6IxQ8BpXic2W:b-3wrlyf) ([raw file](https://github.com/m-lab/autoloader/blob/c324b42810f5ce15f9b81058c553e95789ae00fc/bq/client_test.go#L182)):*
> ```Go
> 			dt := &api.Datatype{Name: tableID}
> 			if tt.schema != "" {
> 				dt.Schema = testingx.MustReadFile(t, tt.schema)
> ```

The `MustReadFile` makes it possible to put these inline during the `tests` declaration above. (and in the next test). Then this assignment can be unconditional.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autoloader/5)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`bq/client_test.go` line 182 at r1](https://reviewable.io/reviews/m-lab/autoloader/5#-NRFc9yU6IxQ8BpXic2V:-NRFzyRMAkD6dFq87F_J:bcujtxn) ([raw file](https://github.com/m-lab/autoloader/blob/c324b42810f5ce15f9b81058c553e95789ae00fc/bq/client_test.go#L182)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The `MustReadFile` makes it possible to put these inline during the `tests` declaration above. (and in the next test). Then this assignment can be unconditional.
</blockquote></details>

Good suggestion! Done.

**Comment by stephen-soltesz** [comment]
(I migrated about 42 repos to the new coveralls github app; the warning that was at the top of the coverall pages are now gone. I expect your next PR to work as you expect )

**Comment by cristinaleonr** [comment]
@stephen-soltesz thank you!

**Pull request merged**
